---

- hosts: 'python'
  tasks:
    - name: "Pull Image from DockerHub"
      become: "yes"
      docker_image:
        name: "{{ docker_image_name }}"
        source: "pull"
    - name: "Create app directory if needed"
      file: "path={{ flask_directory }} state=directory"
    - name: "copy docker-compose to app's server"
      copy:
        src: "{{ docker_compose_dir }}"
        dest: "{{ flask_directory }}"
        owner: "ubuntu"
        group: "ubuntu"
        mode: '0644'
    - name: "Up docker compose"
      command: "docker-compose up -d"
      args:
        chdir: "{{ flask_directory }}"
